### ISSUE TITLE
This plugin has critical dependencies as dev-dependencies

### ISSUE THREAD

**Issue by Karl-Gustav** [jmerrifield/gulp-untar#5]
The plugin breaks if you install it directly with `npm install gulp-untar` and not with adding it to package.json and running `npm install` afterwards.

I have made a pull request that fixes the problem: https://github.com/jmerrifield/gulp-untar/pull/4

**Comment by jmerrifield** [comment]
Fixed with #4, thank you @Karl-Gustav and apologies that you had to fork to get around this

**Comment by Karl-Gustav** [comment]
Thanks for pulling in the merge request! But I'm not the author or `gulp-untar2`, @sorrycc is the author behind the that. (I had a name collision when I tried to make the npm module and found that @sorrycc had beaten me to it)

I would recommend having a look at his repo https://github.com/sorrycc/gulp-untar because he has fixed some other bugs too!
